/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#3e4900",
        "surface-container-high": "#201f1f",
        "primary-container": "#fdd400",
        "surface-container": "#1a1919",
        "on-surface": "#ffffff",
        "inverse-on-surface": "#565554",
        "on-primary-fixed-variant": "#645300",
        "on-secondary-fixed-variant": "#645d00",
        "surface-dim": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "surface-tint": "#ffe483",
        "background": "#0e0e0e",
        "surface-variant": "#262626",
        "primary-fixed": "#fdd400",
        "tertiary": "#f6ffc2",
        "tertiary-fixed-dim": "#d0e862",
        "primary": "#ffe483",
        "on-secondary-fixed": "#454100",
        "error": "#ff7351",
        "on-surface-variant": "#adaaaa",
        "surface": "#0e0e0e",
        "surface-container-highest": "#262626",
        "on-primary-fixed": "#433700",
        "surface-container-low": "#131313",
        "inverse-primary": "#715d00",
        "error-container": "#b92902",
        "tertiary-fixed": "#def76e",
        "tertiary-dim": "#d0e862",
        "on-secondary": "#595300",
        "on-error-container": "#ffd2c8",
        "on-primary-container": "#594a00",
        "on-tertiary": "#566600",
        "secondary-fixed": "#f3e651",
        "outline": "#777575",
        "on-tertiary-container": "#4f5d00",
        "secondary-fixed-dim": "#e4d844",
        "primary-dim": "#edc600",
        "error-dim": "#d53d18",
        "secondary-container": "#676000",
        "tertiary-container": "#def76e",
        "on-primary": "#635200",
        "on-secondary-container": "#fff9d1",
        "outline-variant": "#494847",
        "primary-fixed-dim": "#edc600",
        "on-tertiary-fixed-variant": "#586700",
        "on-background": "#ffffff",
        "secondary": "#f3e651",
        "on-error": "#450900",
        "secondary-dim": "#e4d844",
        "inverse-surface": "#fcf8f8",
        "surface-container-lowest": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
